variables:
  # At the moment, we're building from git master.  This version has better support for (cross-)compiling
  # for Windows.
  # When 0.9.13 is released, we can probably start building off released versions.
  LIBVNC_VERSION: "0.9.12"

jobs:

- job: native_macos
  variables:
    rid: osx-x64
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      wget -nv -nc https://github.com/LibVNC/libvncserver/archive/LibVNCServer-$(LIBVNC_VERSION).tar.gz -O LibVNCServer-$(LIBVNC_VERSION).tar.gz
      tar xzf LibVNCServer-$(LIBVNC_VERSION).tar.gz
    condition: false
    displayName: Download LibVNCServer
  - script: |
      git clone --depth 1 https://github.com/LibVNC/libvncserver/
    displayName: Clone LibVNCServer
  - script: |
      mkdir build
      cd build
      cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/$(rid) ../libvncserver/
    displayName: Configure LibVNC
  - script: |
      make install
    workingDirectory: build
    displayName: Compile LibVNC
  - script: |
      gcc -o $(Build.ArtifactStagingDirectory)/$(rid)/get_offsets -I . -I ../libvncserver/ $(Build.SourcesDirectory)/RemoteViewing.LibVnc/get_offsets.c
      $(Build.ArtifactStagingDirectory)/$(rid)/get_offsets > $(Build.ArtifactStagingDirectory)/$(rid)/get_offsets.txt
    workingDirectory: build
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: libvnc
    displayName: Publish LibVNC

- job: native_windows
  strategy:
    maxParallel: 2
    matrix: 
      x86:
        arch: Win32
        rid: win7-x86
        triplet: x86-windows
      x64:
        arch: x64
        rid: win7-x64
        triplet: x64-windows
  pool:
    vmImage: windows-2019
  steps:
  - script: |
      git clone --depth 1 https://github.com/LibVNC/libvncserver/
    displayName: Clone LibVNCServer
  - task: Cache@2
    inputs:
      key: 'vcpkg_downloads | $(triplet)'
      path: "C:/vcpkg/downloads"
    displayName: Cache VCPKG downloads
  - task: Cache@2
    inputs:
      key: 'vcpkg_installed | $(triplet)'
      path: "C:/vcpkg/installed"
    displayName: Cache VCPKG installed packages
  - script: |
      %VCPKG_INSTALLATION_ROOT%\vcpkg.exe version
      %VCPKG_INSTALLATION_ROOT%\vcpkg.exe install libpng:$(triplet)
      %VCPKG_INSTALLATION_ROOT%\vcpkg.exe install zlib:$(triplet)
      %VCPKG_INSTALLATION_ROOT%\vcpkg.exe install libjpeg-turbo:$(triplet)
    displayName: Install dependencies
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%/scripts/buildsystems/vcpkg.cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/$(rid) ../libvncserver/ -A $(arch)
    displayName: Configure LibVNC
  - script: |
      cmake --build . --target vncserver --config Release
    workingDirectory: build
    displayName: Compile LibVNC
  - script: |
      mkdir $(Build.ArtifactStagingDirectory)\$(rid)\
      echo copy Release\*.* $(Build.ArtifactStagingDirectory)\$(rid)\
      copy Release\*.* $(Build.ArtifactStagingDirectory)\$(rid)\
    workingDirectory: build
    displayName: Install LibVNC
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/'
      artifactName: libvnc
    displayName: Publish LibVNC

- job: native_unix
  pool:
    vmImage: ubuntu-16.04
  variables:
    rid: linux-x64
  container:
    image: ubuntu:20.04
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: |
      sudo apt-get install -y libvncserver-dev gcc
      
      mkdir -p $(Build.ArtifactStagingDirectory)/$(rid)
      gcc -o $(Build.ArtifactStagingDirectory)/$(rid)/get_offsets -I . -I .. $(Build.SourcesDirectory)/RemoteViewing.LibVnc/get_offsets.c
      $(Build.ArtifactStagingDirectory)/$(rid)/get_offsets > $(Build.ArtifactStagingDirectory)/$(rid)/get_offsets.txt
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: libvnc
    displayName: Publish LibVNC

- job: build
  pool:
    vmImage: 'windows-latest'
  dependsOn:
  - native_windows
  - native_macos
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: libvnc
    # Apparently code coverage isn't really supposed to work, but it should work soon. Sigh.
    # https://github.com/microsoft/azure-pipelines-tasks/issues/11677
    # https://github.com/microsoft/azure-pipelines-tasks/issues/9954
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: ' --collect "Code coverage"'
  - script: |
      mkdir $(Build.ArtifactStagingDirectory)/nuget
      dotnet pack -c Release -o $(Build.ArtifactStagingDirectory)/nuget
    displayName: 'Package'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget'
      artifactName: nuget
    condition: true