image: Visual Studio 2019

before_build:
  - cmd: choco install codecov
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release

test_script:
  - cd RemoteViewing.Tests
  - dotnet test RemoteViewing.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: codecov -f "coverage.opencover.xml" -t %CODECOV_TOKEN%
  - cd ..

on_success:
  - cmd: dotnet pack -c Release
  - ps: Push-AppveyorArtifact "RemoteViewing\bin\Release\Quamotion.RemoteViewing.*.nupkg"
  - ps: Push-AppveyorArtifact "RemoteViewing.Windows.Forms\bin\Release\Quamotion.RemoteViewing.Windows.Forms.*.nupkg"
  - ps: Push-AppveyorArtifact "RemoteViewing.AspNetCore\bin\Release\Quamotion.RemoteViewing.AspNetCore.*.nupkg"
  - ps: Push-AppveyorArtifact "RemoteViewing\bin\Release\Quamotion.RemoteViewing.*.snupkg"
  - ps: Push-AppveyorArtifact "RemoteViewing.Windows.Forms\bin\Release\Quamotion.RemoteViewing.Windows.Forms.*.snupkg"
  - ps: Push-AppveyorArtifact "RemoteViewing.AspNetCore\bin\Release\Quamotion.RemoteViewing.AspNetCore.*.snupkg"